### PR TITLE
Add GitHub Actions CI; remove Travis CI; remove AppVeyor CI

### PR DESCRIPTION
**Pull request by DilumAluthge**

### CODE REVIEW

**Comment by DilumAluthge** [comment]
In order to completely disable AppVeyor, someone with admin privileges on this repository will need to go into the repository settings and delete the AppVeyor webhook.

**Comment by DilumAluthge** [comment]
This is ready to review.

**Comment by DilumAluthge** [comment]
Bump @simonbyrne

**Comment by DilumAluthge** [comment]
Bump @staticfloat @StefanKarpinski

**Comment by simonbyrne** [comment]
I'm afraid I don't have admin access.

**Comment by simonbyrne** [comment]
Thanks @DilumAluthge !

**Pull request merged**
