### PR TITLE
Support for precompilation with version check

### PR DESCRIPTION
**Pull request by mdpradeep**

### CODE REVIEW

**Comment by mdpradeep** [comment]
@ViralBShah

**Comment by ViralBShah** [comment]
Would be great to merge this and tag a new release. This greatly helps improve the load times for AWS.jl.

**Comment by ViralBShah** [comment]
Bump @amitmurthy

**Comment by tkelman** [comment]
Technically the version check isn't even necessary here, ref a7224f03d38dc4b72acf8e114a1ea92b3dfbe8f8. Doesn't need to hold this up, but might be good to turn AppVeyor on for this package some time before making the first tag that includes this. I'll open a PR with the appveyor.yml.

**Pull request merged**
