### PR TITLE
Switch to BinaryBuilder

### PR DESCRIPTION
**Pull request by omus**

### CODE REVIEW

**Comment by ararslan** [comment]
Looks like 32-bit Windows support was removed in https://github.com/JuliaWeb/LibCURLBuilder/commit/ffbf3ea3d9b98999a9478566902cb64d64145030#diff-2567705d891d25120e6ea4ca97383113, which explains the 32-bit AppVeyor failures. Everything else is looking good though.

**Comment by omus** [comment]
The 32-bit Windows library is being problematic. I purposefully disabled that part of the LibCURLBuilder and will get back to that later. For now I'll disable the CI tests for 32-bit and proceed from there.

**Comment by omus** [comment]
Note: I tested these changes against https://github.com/invenia/FTPClient.jl/pull/65 since the tests for LibCURL are very inadequate at the moment.

**Comment by omus** [comment]
Wooo! We're ready to go here!

**Comment by omus** [comment]
Fixes: https://github.com/JuliaWeb/LibCURL.jl/issues/44

**Pull request merged**
