### PR TITLE
Drop Julia 0.6 add Julia 1.1

### PR DESCRIPTION
**Pull request by fchorney**

### CODE REVIEW

**Comment by omus** [comment]
"test/ssl.jl" still contains `using Compat` statements

**Comment by fchorney** [comment]
oh yes I see what happened now. I forgot to update my copy of this project with upstream.

**Comment by fchorney** [comment]
There seems to be an issue with downloading the latest julia version

**Comment by fchorney** [comment]
oh I think it's because it calls them "latest" instead of "nightly"

**Comment by omus** [comment]
AppVeyor failure is currently expected.

**Pull request merged**
