### PR TITLE
Enable AppVeyor

### PR DESCRIPTION
**Pull request by tkelman**
needs to be turned on

### CODE REVIEW

**Comment by tkelman** [comment]
Bump @JuliaWeb/contributors can anyone with admin access turn this on?

**Comment by shashi** [comment]
I signed this up https://ci.appveyor.com/project/shashi/libcurl-jl not sure how to test this particular commit. Merge it?

**Comment by tkelman** [comment]
Thanks @shashi! It may require modifying the webhook which only admins can do, but may as well see if merging does anything.

**Comment by tkelman** [comment]
I see it at https://ci.appveyor.com/project/shashi/libcurl-jl/history, looks good. Could add the readme badge if it passes? And dunno if the webhook will work right on PR's, but we can fix that later if needed.

**Comment by shashi** [comment]
done :+1:

**Comment by tkelman** [comment]
Did you trigger build 2 manually? Merging #27 should have started a new build if the webhook were worjing. Can you go to the settings on appveyor and copy paste the webhook url here? Then one of the admins will have to configure it on the github side, ref https://github.com/JuliaOpt/JuMP.jl/pull/362#issuecomment-70610293

**Comment by shashi** [comment]
It looks like I'm not admin enough for that. https://github.com/JuliaWeb/LibCURL.jl/settings gives me 404

**Comment by tkelman** [comment]
Someone else will need to do it, but you need to provide them with the destination webhook url from your appveyor settings. It's still a pretty annoying process if you are a committer but not an owner of a repo. cc @feodorfitsner

**Pull request merged**
