### PR TITLE
Changed `is_windows` to `Sys.iswindows` 

### PR DESCRIPTION
**Pull request by danimad**
Changed `is_windows` to `Sys.iswindows` because it was deprecated with [JuliaLang/julia#22182](https://github.com/JuliaLang/julia/pull/22182)

### CODE REVIEW

**Comment by ranjanan** [comment]
You've got to update travis and appveyor to test only from v0.7

**Comment by danimad** [comment]
@ranjanan Thanks! But should I just updated it so they test v0.7 and up, or should I try to make it compatible with older versions somehow?
I'm just getting into Julia, and wanted to try out Queryverse with v1.0, and now I try to fix the errors on my local machines. Maybe it was a bit presumptuous to do PLs until I learned more about Julia.  😄

**Comment by danimad** [comment]
Not yet, but thanks for showing it to me. I played around more and I saw that these things should also be changed. I look at #42 maybe I can help there.

**Comment by omus** [comment]
#42 is now merged. Note that Julia 1.0 doesn't quite work yet.

**Pull request closed without merging**
